name = "gl_wasm"
version = "1.2.0"

description = "Create binary WebAssembly modules in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gertvv", repo = "gl_wasm" }

[dependencies]
gleb128 = ">= 4.0.0 and < 5.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
ieee_float = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.4.0 and < 2.0.0"
wasmex = ">= 0.14.0 and < 1.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
